apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dyna-hpa-http-requests-total
  namespace: dynatrace-poc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dynatrace-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metric:
        name: http_server_requests_seconds_count
        selector: "app=dynatrace-app"
      target:
        type: AverageValue
        averageValue: 200
