apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dyna-hpa-http-requests-total
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dynatrace-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: http_server_requests_seconds_count
      target:
        type: AverageValue
        averageValue: 25
