apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dyna-hpa-memory-utilization
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dynatrace-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi
