apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dyna-hpa-jvm-live-threads-count
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dynatrace-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: jvm_threads_live
      target:
        type: AverageValue
        averageValue: 15.0
